"""SQLite storage helpers for parsed authentication events."""

import sqlite3
from pathlib import Path
from typing import NotRequired, TypedDict

from parser import AuthEvent


DEFAULT_DATABASE_PATH = (
    Path(__file__).resolve().parent.parent / "data" / "threat_log.db"
)


class StoredAuthEvent(TypedDict):
    """An authentication event after SQLite assigns its numeric ID."""

    id: int
    timestamp: str
    event_timestamp: str | None
    username: str
    ip_address: str
    event_type: str
    is_invalid_user: bool
    raw_message: str


class Alert(TypedDict):
    """A security alert generated by a detection rule."""

    alert_type: str
    title: str
    severity: str
    source_ip: str
    event_count: int
    distinct_username_count: NotRequired[int | None]
    username: NotRequired[str | None]
    window_start: str
    window_end: str
    successful_login_timestamp: NotRequired[str | None]
    description: str
    recommendation: str


class StoredAlert(Alert):
    """A security alert after SQLite adds its ID and creation time."""

    id: int
    created_at: str


def open_database(database_path: str | Path = DEFAULT_DATABASE_PATH) -> sqlite3.Connection:
    """Open a SQLite connection and create its parent directory if necessary."""
    path = Path(database_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    return sqlite3.connect(path)


def create_auth_events_table(connection: sqlite3.Connection) -> None:
    """Create the auth_events table when it does not already exist."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            event_timestamp TEXT,
            username TEXT NOT NULL,
            ip_address TEXT NOT NULL,
            event_type TEXT NOT NULL,
            is_invalid_user INTEGER NOT NULL DEFAULT 0
                CHECK (is_invalid_user IN (0, 1)),
            raw_message TEXT NOT NULL UNIQUE
        )
        """
    )

    # Legacy rows retain their original evidence. Their unknown year is not guessed.
    existing_columns = {
        row[1] for row in connection.execute("PRAGMA table_info(auth_events)")
    }
    if "event_timestamp" not in existing_columns:
        connection.execute("ALTER TABLE auth_events ADD COLUMN event_timestamp TEXT")
    if "is_invalid_user" not in existing_columns:
        connection.execute(
            "ALTER TABLE auth_events "
            "ADD COLUMN is_invalid_user INTEGER NOT NULL DEFAULT 0"
        )
        connection.execute(
            """
            UPDATE auth_events
            SET is_invalid_user = 1
            WHERE raw_message LIKE '%invalid user%'
            """
        )
    connection.commit()


def create_alerts_table(connection: sqlite3.Connection) -> None:
    """Create the alerts table when it does not already exist."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            alert_type TEXT NOT NULL,
            title TEXT NOT NULL,
            severity TEXT NOT NULL,
            source_ip TEXT NOT NULL,
            event_count INTEGER NOT NULL,
            distinct_username_count INTEGER,
            username TEXT,
            window_start TEXT,
            window_end TEXT,
            successful_login_timestamp TEXT,
            description TEXT NOT NULL,
            recommendation TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (alert_type, source_ip, window_start, window_end)
        )
        """
    )

    existing_columns = {
        row[1] for row in connection.execute("PRAGMA table_info(alerts)").fetchall()
    }
    additions = {
        "distinct_username_count": "INTEGER",
        "username": "TEXT",
        "window_start": "TEXT",
        "window_end": "TEXT",
        "successful_login_timestamp": "TEXT",
    }
    for column_name, column_type in additions.items():
        if column_name not in existing_columns:
            connection.execute(
                f"ALTER TABLE alerts ADD COLUMN {column_name} {column_type}"
            )

    table_sql = connection.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'alerts'"
    ).fetchone()[0]
    if "UNIQUE (alert_type, source_ip, event_count)" in table_sql:
        # SQLite cannot drop a table-level UNIQUE constraint, so rebuild in place.
        connection.execute(
            """
            CREATE TABLE alerts_milestone5 (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                alert_type TEXT NOT NULL,
                title TEXT NOT NULL,
                severity TEXT NOT NULL,
                source_ip TEXT NOT NULL,
                event_count INTEGER NOT NULL,
                distinct_username_count INTEGER,
                username TEXT,
                window_start TEXT,
                window_end TEXT,
                successful_login_timestamp TEXT,
                description TEXT NOT NULL,
                recommendation TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (alert_type, source_ip, window_start, window_end)
            )
            """
        )
        connection.execute(
            """
            INSERT INTO alerts_milestone5 (
                id, alert_type, title, severity, source_ip, event_count,
                distinct_username_count, username, window_start, window_end,
                successful_login_timestamp, description, recommendation,
                created_at
            )
            SELECT id, alert_type, title, severity, source_ip, event_count,
                   distinct_username_count, username, window_start, window_end,
                   successful_login_timestamp, description, recommendation,
                   created_at
            FROM alerts
            """
        )
        connection.execute("DROP TABLE alerts")
        connection.execute("ALTER TABLE alerts_milestone5 RENAME TO alerts")

    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS alerts_window_identity
        ON alerts (alert_type, source_ip, window_start, window_end)
        WHERE window_start IS NOT NULL AND window_end IS NOT NULL
        """
    )
    connection.commit()


def insert_auth_event(connection: sqlite3.Connection, event: AuthEvent) -> bool:
    """Insert one event and return True, or return False if it is a duplicate."""
    cursor = connection.execute(
        """
        INSERT OR IGNORE INTO auth_events
            (timestamp, event_timestamp, username, ip_address, event_type,
             is_invalid_user, raw_message)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            event["timestamp"],
            event["event_timestamp"],
            event["username"],
            event["ip_address"],
            event["event_type"],
            int(event["is_invalid_user"]),
            event["raw_message"],
        ),
    )
    inserted = cursor.rowcount == 1
    if not inserted:
        connection.execute(
            """
            UPDATE auth_events
            SET event_timestamp = COALESCE(event_timestamp, ?),
                is_invalid_user = ?
            WHERE raw_message = ?
            """,
            (
                event["event_timestamp"],
                int(event["is_invalid_user"]),
                event["raw_message"],
            ),
        )
    connection.commit()
    return inserted


def insert_auth_events(
    connection: sqlite3.Connection, events: list[AuthEvent]
) -> int:
    """Insert several events and return the number of new rows stored."""
    inserted_count = 0

    # One transaction makes a group insert consistent and avoids repeated commits.
    with connection:
        for event in events:
            cursor = connection.execute(
                """
                INSERT OR IGNORE INTO auth_events
                    (timestamp, event_timestamp, username, ip_address, event_type,
                     is_invalid_user, raw_message)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    event["timestamp"],
                    event["event_timestamp"],
                    event["username"],
                    event["ip_address"],
                    event["event_type"],
                    int(event["is_invalid_user"]),
                    event["raw_message"],
                ),
            )
            inserted_count += cursor.rowcount
            if cursor.rowcount == 0:
                connection.execute(
                    """
                    UPDATE auth_events
                    SET event_timestamp = COALESCE(event_timestamp, ?),
                        is_invalid_user = ?
                    WHERE raw_message = ?
                    """,
                    (
                        event["event_timestamp"],
                        int(event["is_invalid_user"]),
                        event["raw_message"],
                    ),
                )

    return inserted_count


def get_all_auth_events(connection: sqlite3.Connection) -> list[StoredAuthEvent]:
    """Retrieve every stored event in insertion order."""
    cursor = connection.execute(
        """
        SELECT id, timestamp, event_timestamp, username, ip_address, event_type,
               is_invalid_user, raw_message
        FROM auth_events
        ORDER BY id
        """
    )

    return [
        {
            "id": row[0],
            "timestamp": row[1],
            "event_timestamp": row[2],
            "username": row[3],
            "ip_address": row[4],
            "event_type": row[5],
            "is_invalid_user": bool(row[6]),
            "raw_message": row[7],
        }
        for row in cursor.fetchall()
    ]


def insert_alert(connection: sqlite3.Connection, alert: Alert) -> bool:
    """Insert one alert and return False when that alert already exists."""
    cursor = connection.execute(
        """
        INSERT OR IGNORE INTO alerts
            (alert_type, title, severity, source_ip, event_count,
             distinct_username_count, username, window_start, window_end,
             successful_login_timestamp, description, recommendation)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            alert["alert_type"],
            alert["title"],
            alert["severity"],
            alert["source_ip"],
            alert["event_count"],
            alert.get("distinct_username_count"),
            alert.get("username"),
            alert["window_start"],
            alert["window_end"],
            alert.get("successful_login_timestamp"),
            alert["description"],
            alert["recommendation"],
        ),
    )
    connection.commit()
    return cursor.rowcount == 1


def insert_alerts(connection: sqlite3.Connection, alerts: list[Alert]) -> int:
    """Insert several alerts and return the number of new rows stored."""
    inserted_count = 0

    with connection:
        for alert in alerts:
            cursor = connection.execute(
                """
                INSERT OR IGNORE INTO alerts
                    (alert_type, title, severity, source_ip, event_count,
                     distinct_username_count, username, window_start, window_end,
                     successful_login_timestamp, description, recommendation)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    alert["alert_type"],
                    alert["title"],
                    alert["severity"],
                    alert["source_ip"],
                    alert["event_count"],
                    alert.get("distinct_username_count"),
                    alert.get("username"),
                    alert["window_start"],
                    alert["window_end"],
                    alert.get("successful_login_timestamp"),
                    alert["description"],
                    alert["recommendation"],
                ),
            )
            inserted_count += cursor.rowcount

    return inserted_count


def get_all_alerts(connection: sqlite3.Connection) -> list[StoredAlert]:
    """Retrieve all stored alerts in insertion order."""
    cursor = connection.execute(
        """
        SELECT id, alert_type, title, severity, source_ip, event_count,
               distinct_username_count, username, description, recommendation,
               created_at, window_start, window_end, successful_login_timestamp
        FROM alerts
        ORDER BY id
        """
    )

    return [
        {
            "id": row[0],
            "alert_type": row[1],
            "title": row[2],
            "severity": row[3],
            "source_ip": row[4],
            "event_count": row[5],
            "distinct_username_count": row[6],
            "username": row[7],
            "description": row[8],
            "recommendation": row[9],
            "created_at": row[10],
            "window_start": row[11],
            "window_end": row[12],
            "successful_login_timestamp": row[13],
        }
        for row in cursor.fetchall()
    ]
