"""SQLite storage helpers for parsed authentication events."""

import sqlite3
from pathlib import Path
from typing import TypedDict

from parser import AuthEvent


DEFAULT_DATABASE_PATH = (
    Path(__file__).resolve().parent.parent / "data" / "threat_log.db"
)


class StoredAuthEvent(TypedDict):
    """An authentication event after SQLite assigns its numeric ID."""

    id: int
    timestamp: str
    username: str
    ip_address: str
    event_type: str
    raw_message: str


class Alert(TypedDict):
    """A security alert generated by a detection rule."""

    alert_type: str
    title: str
    severity: str
    source_ip: str
    event_count: int
    description: str
    recommendation: str


class StoredAlert(Alert):
    """A security alert after SQLite adds its ID and creation time."""

    id: int
    created_at: str


def open_database(database_path: str | Path = DEFAULT_DATABASE_PATH) -> sqlite3.Connection:
    """Open a SQLite connection and create its parent directory if necessary."""
    path = Path(database_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    return sqlite3.connect(path)


def create_auth_events_table(connection: sqlite3.Connection) -> None:
    """Create the auth_events table when it does not already exist."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            username TEXT NOT NULL,
            ip_address TEXT NOT NULL,
            event_type TEXT NOT NULL,
            raw_message TEXT NOT NULL UNIQUE
        )
        """
    )
    connection.commit()


def create_alerts_table(connection: sqlite3.Connection) -> None:
    """Create the alerts table when it does not already exist."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            alert_type TEXT NOT NULL,
            title TEXT NOT NULL,
            severity TEXT NOT NULL,
            source_ip TEXT NOT NULL,
            event_count INTEGER NOT NULL,
            description TEXT NOT NULL,
            recommendation TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (alert_type, source_ip, event_count)
        )
        """
    )
    connection.commit()


def insert_auth_event(connection: sqlite3.Connection, event: AuthEvent) -> bool:
    """Insert one event and return True, or return False if it is a duplicate."""
    cursor = connection.execute(
        """
        INSERT OR IGNORE INTO auth_events
            (timestamp, username, ip_address, event_type, raw_message)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            event["timestamp"],
            event["username"],
            event["ip_address"],
            event["event_type"],
            event["raw_message"],
        ),
    )
    connection.commit()
    return cursor.rowcount == 1


def insert_auth_events(
    connection: sqlite3.Connection, events: list[AuthEvent]
) -> int:
    """Insert several events and return the number of new rows stored."""
    inserted_count = 0

    # One transaction makes a group insert consistent and avoids repeated commits.
    with connection:
        for event in events:
            cursor = connection.execute(
                """
                INSERT OR IGNORE INTO auth_events
                    (timestamp, username, ip_address, event_type, raw_message)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    event["timestamp"],
                    event["username"],
                    event["ip_address"],
                    event["event_type"],
                    event["raw_message"],
                ),
            )
            inserted_count += cursor.rowcount

    return inserted_count


def get_all_auth_events(connection: sqlite3.Connection) -> list[StoredAuthEvent]:
    """Retrieve every stored event in insertion order."""
    cursor = connection.execute(
        """
        SELECT id, timestamp, username, ip_address, event_type, raw_message
        FROM auth_events
        ORDER BY id
        """
    )

    return [
        {
            "id": row[0],
            "timestamp": row[1],
            "username": row[2],
            "ip_address": row[3],
            "event_type": row[4],
            "raw_message": row[5],
        }
        for row in cursor.fetchall()
    ]


def insert_alert(connection: sqlite3.Connection, alert: Alert) -> bool:
    """Insert one alert and return False when that alert already exists."""
    cursor = connection.execute(
        """
        INSERT OR IGNORE INTO alerts
            (alert_type, title, severity, source_ip, event_count,
             description, recommendation)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            alert["alert_type"],
            alert["title"],
            alert["severity"],
            alert["source_ip"],
            alert["event_count"],
            alert["description"],
            alert["recommendation"],
        ),
    )
    connection.commit()
    return cursor.rowcount == 1


def insert_alerts(connection: sqlite3.Connection, alerts: list[Alert]) -> int:
    """Insert several alerts and return the number of new rows stored."""
    inserted_count = 0

    with connection:
        for alert in alerts:
            cursor = connection.execute(
                """
                INSERT OR IGNORE INTO alerts
                    (alert_type, title, severity, source_ip, event_count,
                     description, recommendation)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    alert["alert_type"],
                    alert["title"],
                    alert["severity"],
                    alert["source_ip"],
                    alert["event_count"],
                    alert["description"],
                    alert["recommendation"],
                ),
            )
            inserted_count += cursor.rowcount

    return inserted_count


def get_all_alerts(connection: sqlite3.Connection) -> list[StoredAlert]:
    """Retrieve all stored alerts in insertion order."""
    cursor = connection.execute(
        """
        SELECT id, alert_type, title, severity, source_ip, event_count,
               description, recommendation, created_at
        FROM alerts
        ORDER BY id
        """
    )

    return [
        {
            "id": row[0],
            "alert_type": row[1],
            "title": row[2],
            "severity": row[3],
            "source_ip": row[4],
            "event_count": row[5],
            "description": row[6],
            "recommendation": row[7],
            "created_at": row[8],
        }
        for row in cursor.fetchall()
    ]
